name: ubuntu-docviewer-app
version: 2.1.350
summary: Document Viewer
description: Document Viewer application for Ubuntu devices
confinement: strict
grade: devel

apps:
    ubuntu-docviewer-app:
        command: desktop-launch $SNAP/usr/bin/ubuntu-docviewer-app ---documentsDir=$(HOME=/home/$USER xdg-user-dir DOCUMENTS) "$@"
        plugs:
            - home
            - opengl
            - platform
            - unity7
            - unity8
            - mir

plugs:
    platform:
        interface: content
        content: ubuntu-app-platform1
        target: ubuntu-app-platform
        default-provider: ubuntu-app-platform

parts:
    ubuntu-docviewer-app:
        plugin: cmake
        configflags: [-DCMAKE_INSTALL_PREFIX=/usr, -DCLICK_MODE=off]
        source: .
        build-packages:
            - cmake
            - intltool
            - libpoppler-qt5-dev
            - qtbase5-private-dev
            - qtdeclarative5-private-dev
            - qtdeclarative5-qtquick2-plugin
        stage-packages:
            - qtdeclarative5-poppler1.0
            - xdg-user-dirs
        snap:
            # ubuntu-docviewer-app
            - usr/bin/ubuntu-docviewer-app
            - usr/share/applications
            - usr/share/locale
            - usr/share/ubuntu-docviewer-app

            # qtdeclarative5-documentviewer-common
            # qtdeclarative5-documentviewer-libreoffice
            # qtdeclarative5-documentviewer-pdf
            - usr/lib/*/qt5/qml/DocumentViewer

            # qtdeclarative5-poppler1.0
            - usr/lib/*/qt5/qml/org/docviewer
            - usr/share/doc/qtdeclarative5-poppler1.0/copyright

            # xdg-user-dirs
            - usr/share/locale/*/LC_MESSAGES/xdg-user-dirs.mo
            - usr/bin/xdg-user-dir
            - usr/bin/xdg-user-dirs-update
            - etc/xdg/user-dirs.conf
            - etc/xdg/user-dirs.defaults
            - etc/X11/Xsession.d/60xdg-user-dirs-update
            - usr/share/doc/xdg-user-dirs/copyright
            - usr/share/doc/xdg-user-dirs/AUTHORS

    platform:
        plugin: dump
        source: snap
        after: [desktop-ubuntu-app-platform]
        snap: [ubuntu-app-platform]
